name: DataMiner CICD Internal Nuget Solution
on:
  push:
    branches:
    - main
    - master
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+'
  workflow_dispatch: 
jobs:
  CICD:
    name: CICD
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Internal NuGet Solution Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: todo
    secrets:
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
      nugetApiKey: ${{ secrets.NUGETAPIKEY_GITHUB  }}
