name: DataMiner CICD Automation
on:
  push:
    branches: []
    tags:
    - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+'
  workflow_dispatch: 
jobs:
  CI:
    name: CI
    uses: SkylineCommunications/_ReusableWorkflows/.github/workflows/Automation Master Workflow.yml@main
    with:
      referenceName: ${{ github.ref_name }}
      runNumber: ${{ github.run_number }}
      referenceType: ${{ github.ref_type }}
      repository: ${{ github.repository }}
      owner: ${{ github.repository_owner }}
      sonarCloudProjectName: ''
    secrets:
      api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
      sonarCloudToken: ${{ secrets.SONAR_TOKEN }}
  CD:
    if: github.ref_type == 'tag'
    environment: production
    name: CD
    runs-on: ubuntu-latest
    needs: CI
    steps:
    - uses: actions/checkout@v3
    - name: Skyline DataMiner Deploy Action
      uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1
      with:
        stage: Deploy
        api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
        artifact-id: ${{ needs.CI.outputs.artifact-id }}
